### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by moto25** [dhewg/esphome-miot#23]
Hi, since ESPHome 2024.6.0 are OTA changes. When setting

ota:
  - platform: esphome  
    password: !secret ota_password

got compile error:

src/esphome/components/miot/miot.cpp:18:10: fatal error: esphome/components/ota/ota_component.h: No such file or directory
 #include "esphome/components/ota/ota_component.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/mi-gbr/src/esphome/components/miot/miot.o] Error 1

any idea? thank you

**Comment by scrampker** [comment]
This is a change to ESPHome. You would update that section to:

ota:
  platform: esphome


That being said, I'm still getting the following afterwards, which means the actual libraries need to be updated:
![image](https://github.com/dhewg/esphome-miot/assets/15056860/82f0206e-21fd-4dc9-8244-01e7309f8267)

**Comment by 9R** [comment]
#25 is an alternate solution for this issue that makes use of the new esphome function `get_global_ota_callback()`

**Comment by dhewg** [comment]
I just merged the fix, thanks everybody!
