### ISSUE TITLE
add air purifier 4 pro to the supported devices

### ISSUE THREAD

**Issue by duckimann** [dhewg/esphome-miot#30]
I've flashed my air purifier using the config `zhimi.airp.mb5.yaml`

Board: AC-M15-SC_B01
Board img:
![image](https://github.com/user-attachments/assets/ddec8975-6bbe-4279-9491-238ddd832a67)

Pinout:
J5:
- GND
- GPIO0

J4 (by wire color):
- Purple: GND
- Blue: RXD
- Green: TXD

Other:
- `PW` pad (with white wire soldered on it)

Any other modification i have to do:
- Change external component source to `github://9R/esphome-miot@main` as [mentioned in this](https://github.com/dhewg/esphome-miot/pull/25#issuecomment-2226935619)

**Comment by dhewg** [comment]
If this is `https://home.miot-spec.com/spec/zhimi.airp.vb4` it's very similar to `zhimi.airp.mb5` indeed, but there are differences in SIID:PIID:
3:8 new
3:9 new
9:11 gone
9:12 new
15:1 new

So I think we should add it's own config for it.
Do you want to do that and open a PR for it here?
Thanks!
